### ISSUE TITLE
Does this support Dynamic Height and Virtualization?

### ISSUE THREAD

**Issue by DaleSalcedo** [Forecast-it/react-virtualized-dnd#23]
I tried implementing this just now but I wasn't sure if this supports dynamic height though I saw a closed ticket regarding it so I assume it does?

I cannot figure out how to implement that though..  React-Virtualized relies on the AutoSizer but I see nothing similar in these docs nor the given example that I can use similarly.

I tried giving static heights as well just to see it run but the playlist definitely didn't seem virtualized neither.

Any help or tips would be great, thank you.

**Comment by LukasTvegaard** [comment]
Unlike with many other Virtualization frameworks, handling of Dynamic Height elements is integrated into the Virtualization logic.

One of the examples contains a demonstration of a Virtualized Droppable with dynamic height Draggables: src/examples/example-dynamic.js

The key is setting the "dynamicElemHeight" and "minElemHeight" properties on the Droppable.

It should be noted that the current implementation of Dynamic Height Virtualization has a flaw that we have not been able to solve, where the Virtualization can fail to "catch up" if you rapidly change the scroll-direction while scrolling. Unfortunately, we do not expect to have this issue resolved anytime soon since it has turned out to be an extremely complex problem.

**Comment by DaleSalcedo** [comment]
Thank you for responding and help.  Will try to get this to work again today.  Please give me a day or two to close the ticket incase I run into further issues

**Comment by DaleSalcedo** [comment]
Actually I didn't describe correctly.  I just needed the container that holds the playlist to be dynamic in height and not a fixed height.  So that being explained properly now, does this library support that?

**Comment by DaleSalcedo** [comment]
The drag and drop is working, but I do not see the virtualization working, do you see anything I'm doing wrong?  I put in values for scrollContainerHeight and containerHeight just to try to see this working first before moving further... that being said, ideally am I wrong in my assumption that both those values should be matching?

`<DragDropContext
        dragAndDropGroup="playlist"
        // onDragEnd={(e) => // TODO }
        scrollContainerHeight={500}
      >
        <div className="actual-playlist">
          <Droppable
            containerHeight={500}
            dragAndDropGroup="playlist"
            droppableId="droppableId"
          >
            {
              playlistPageIds.map((id) => (
                <Draggable
                  dragAndDropGroup="playlist"
                  draggableId={id}
                  key={id}
                >
                  <Page
                    composition={composition}
                    id={id}
                    key={id}
                    preview={preview}
                  />
                </Draggable>
              ))
            }
          </Droppable>
        </div>
      </DragDropContext>`

**Comment by DaleSalcedo** [comment]
I tried below as well, but getting an error in the console:

"Warning: `NaN` is an invalid value for the `height` css style property.
    in div (created by Droppable)
    in Droppable (at Playlist.jsx:30)"

Not sure what I'm doing wrong here but seems like I'm not getting anywhere. Looking for more direction if possible

```
return (
      <DragDropContext
        dragAndDropGroup={name}
        onDragEnd={() => console.log('sort')}
        outerScrollBar
      >
        <div className="your-drag-container">
          {activePlaylistPages.map((id) => (
            <div className="your-droppable-container" key={id}>
              <Droppable
                containerHeight={500}
                dragAndDropGroup={name}
                droppableId={id}
                key={id}
              >
                <Draggable
                  dragAndDropGroup={name}
                  draggableId={id}
                >
                  <div className="your-draggable-element">
                    <p>
                      {id}
                    </p>
                  </div>
                </Draggable>
              </Droppable>
            </div>
          ))}
        </div>
      </DragDropContext>
    );
```

**Comment by LukasTvegaard** [comment]
For your second example, you always need to set the scrollContainerHeight on the DragDropContext when using outerScrollBar. The framework supports variable container height to the extent that you can supply a variable value to the height-properties (so you could for instance say scrollContainerHeight={window.innerHeight) if you want your context to span the entire height of the screen). The height of the DragDropContext and the height of the Droppable does not have to be equal - the only limitation is that your Droppable should fit within the context.

For why you are not seeing the virtualization, there is a few elements worth of overscan both on top and on bottom, so you need a list significantly longer than the height of your Droppable to see an effect. I would also recommend setting either the "rowHeight" property if you are using fixed-height Draggables, or the dynamicElemHeight property if you expect elements to have different heights.

Finally, remember to set a key on your Draggables, otherwise React will have trouble telling your elements in the List apart.

**Comment by DaleSalcedo** [comment]
Hey thank you for the in-detail response.  I went back to the first code snippet in a branch i committed and actually the virtualization worked.  But now it's not working again even though I reset back to the original commit and I can't get it to work again.  

- the Draggable and child element both have keys.
- I set the Droppable "rowHeight" to match the same pixel number as in the CSS class
- I removed the scrollContainerHeight in the DragDropContext
- I changed the containerHeight to just 100 this time, again just to make sure it all works.  I generate a list of 90 items so my list is definitely bigger than the container

Still can't seem to get the virtualization to work.. Here's a screen shot that may tell you something or it may not.  If you have no idea what's going on that's okay too and i'll just close the ticket and move on.  Thanks again

[screenshot](https://imgur.com/a/BhyO98F)

```
return (
      <DragDropContext
        dragAndDropGroup="playlist"
        // onDragEnd={(e) => // TODO
      >
        <div className="actual-playlist">
          <Droppable
            containerHeight={100}
            dragAndDropGroup="playlist"
            droppableId="droppableId"
            rowHeight={44}
          >
            {
              playlistPageIds.map((id) => (
                <Draggable
                  dragAndDropGroup="playlist"
                  draggableId={id}
                  key={id}
                >
                  <Page
                    composition={composition}
                    id={id}
                    key={id}
                    preview={preview}
                  />
                </Draggable>
              ))
            }
          </Droppable>
        </div>
      </DragDropContext>
    );
```

**Comment by DaleSalcedo** [comment]
Thank you for trying to help!
